const NULL_EL={set textContent(v){},set innerHTML(v){},set className(v){},set href(v){},set value(v){},classList:{add(){},remove(){},toggle(){},contains:()=>false},addEventListener(){},style:{},querySelector(){return null},querySelectorAll(){return[]}};
const $ = id => document.getElementById(id) || NULL_EL;
const state = {market:null, products:[], fundamentals:{}, seats:{}, essays:{}, equity:{}, newsItems:[], filtered:[], sector:'全部', view:'cards', detail:null, frame:'D', strategyFrame:'D'};
const sectors=['全部','有色','贵金属','黑色','能化','农产品','金融','其他'];
const fmt=(v,d)=>v==null||Number.isNaN(+v)?'—':Number(v).toLocaleString('zh-CN',{minimumFractionDigits:d??(Math.abs(+v)<100?2:0),maximumFractionDigits:d??(Math.abs(+v)<100?2:0)});
const signed=(v,d=2)=>`${+v>=0?'+':''}${fmt(v,d)}`;
const cls=t=>t==='up'?'tone-up':t==='down'?'tone-down':'tone-neutral';
const dl=pairs=>pairs.map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('');
const range=v=>`${fmt(v?.[0])} — ${fmt(v?.[1])}`;

const cssv=(n,f)=>{const v=getComputedStyle(document.body).getPropertyValue(n).trim();return v||f};
function applyTheme(t){document.body.classList.toggle('theme-journal',t==='journal');localStorage.setItem('yafco-theme',t);const b=$('themeToggle');if(b)b.textContent=t==='journal'?'🌊 深渊风':'🌿 手账风';if(state.detail)renderChart()}
function initTheme(){const q=new URLSearchParams(location.search).get('theme');applyTheme(q==='journal'||q==='abyss'?q:(localStorage.getItem('yafco-theme')||'abyss'));const b=$('themeToggle');if(b)b.addEventListener('click',e=>{e.preventDefault();applyTheme(document.body.classList.contains('theme-journal')?'abyss':'journal')})}

async function fetchJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
async function refreshLive(){if(!booted||!window.YAFCOAccess?.allowed()||!state.market)return;try{const next=await fetchJSON(`data/market.json?t=${Date.now()}`);if(!next?.updated_at||next.updated_at===state.market.updated_at)return;state.market=next;state.products=next.products||[];renderMeta();renderRadar();applyFilters();renderDailyPicks();renderFocusPool();renderDivBoard();if(state.detail?.product?.product){const symbol=state.detail.product.product;state.detail=await fetchJSON(`data/symbols/${symbol}.json?t=${Date.now()}`);renderDetail(state.detail)}}catch(e){console.warn('live snapshot refresh skipped',e)}}
async function init(){try{state.market=await fetchJSON(`data/market.json?t=${Date.now()}`);state.products=state.market.products||[];try{const f=await fetchJSON(`data/fundamentals.json?t=${Date.now()}`);state.fundamentals=Object.fromEntries((f.products||[]).map(x=>[x.symbol,x]))}catch(e){console.warn('fundamentals unavailable',e)}try{const s=await fetchJSON(`data/seats.json?t=${Date.now()}`);state.seats=s.products||{}}catch(e){console.warn('seats unavailable',e)}try{const z=await fetchJSON(`data/zsxq.json?t=${Date.now()}`);state.essays=z.by_symbol||{}}catch(e){console.warn('essays unavailable',e)}try{const q=await fetchJSON(`data/equity.json?t=${Date.now()}`);state.equity=q.products||{}}catch(e){console.warn('equity unavailable',e)}renderMeta();renderFilters();renderRadar();applyFilters();bind();renderDailyPicks();renderFocusPool();renderDivBoard();setTimeout(()=>$('loadingScreen').classList.add('done'),420);const hash=location.hash.match(/symbol=([A-Z0-9]+)/i);if(hash)openDetail(hash[1].toUpperCase(),false)}catch(e){$('loadingScreen').querySelector('span').textContent=`数据链路失败：${e.message}`;toast(e.message)}}
function bind(){$('searchInput').addEventListener('input',applyFilters);$('sortSelect').addEventListener('change',applyFilters);$('sectorFilters').addEventListener('click',e=>{if(!e.target.dataset.sector)return;state.sector=e.target.dataset.sector;renderFilters();applyFilters()});document.querySelector('.scanner-summary div').addEventListener('click',e=>{if(!e.target.dataset.view)return;state.view=e.target.dataset.view;document.querySelectorAll('.scanner-summary button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));renderProducts()});$('productGrid').addEventListener('click',e=>{const card=e.target.closest('[data-symbol]');if(card)openDetail(card.dataset.symbol)});$('productTable').addEventListener('click',e=>{const row=e.target.closest('[data-symbol]');if(row)openDetail(row.dataset.symbol)});const dp=$('dailyPicks');if(dp)dp.addEventListener('click',e=>{const it=e.target.closest('[data-symbol]');if(it)openDetail(it.dataset.symbol)});const fp=$('focusPool');if(fp)fp.addEventListener('click',e=>{const it=e.target.closest('[data-symbol]');if(it)openDetail(it.dataset.symbol)});$('bullRank').addEventListener('click',rankClick);$('bearRank').addEventListener('click',rankClick);$('closeDetail').addEventListener('click',()=>{location.hash='detail';$('detailShell').classList.add('hidden');$('detailEmpty').classList.remove('hidden')});$('chartTabs').addEventListener('click',e=>{if(!e.target.dataset.frame)return;state.frame=e.target.dataset.frame;document.querySelectorAll('#chartTabs button').forEach(b=>b.classList.toggle('active',b.dataset.frame===state.frame));renderChart()});$('strategyTabs').addEventListener('click',e=>{if(!e.target.dataset.frame)return;state.strategyFrame=e.target.dataset.frame;document.querySelectorAll('#strategyTabs button').forEach(b=>b.classList.toggle('active',b.dataset.frame===state.strategyFrame));renderStrategy()});$('coverRandom').addEventListener('click',()=>{const p=state.products[Math.floor(Math.random()*state.products.length)];openDetail(p.symbol)});}
function divScatterSVG(rows){if(!rows.length)return '';
const W=560,H=320,PL=46,PR=16,PT=14,PB=34;
const xs=rows.map(r=>r.comm),ys=rows.map(r=>r.basket);
let x0=Math.min(...xs,-5),x1=Math.max(...xs,5),y0=Math.min(...ys,-5),y1=Math.max(...ys,5);
const px=(x1-x0)*.08,py=(y1-y0)*.08;x0-=px;x1+=px;y0-=py;y1+=py;
const X=v=>PL+(v-x0)/(x1-x0)*(W-PL-PR),Y=v=>PT+(y1-v)/(y1-y0)*(H-PT-PB);
const gc=cssv('--chart-grid','#17333d'),gt=cssv('--chart-text','#789198');
let s=`<line x1="${X(x0)}" y1="${Y(0)}" x2="${X(x1)}" y2="${Y(0)}" stroke="${gc}"/><line x1="${X(0)}" y1="${Y(y0)}" x2="${X(0)}" y2="${Y(y1)}" stroke="${gc}"/>`;
const dl=Math.max(x1,y1),dl0=Math.min(x0,y0);
s+=`<line x1="${X(dl0)}" y1="${Y(dl0)}" x2="${X(dl)}" y2="${Y(dl)}" stroke="${cssv('--amber','#dfb364')}" stroke-dasharray="6 4" stroke-width="1"/>`;
s+=`<text x="${X(dl)-170}" y="${Y(dl)+16}" fill="${gt}" font-size="9">对角线=股商同步</text>`;
for(const r of rows){const hot=Math.abs(r.div)>=6;const col=r.div>=6?cssv('--green','#57d6a5'):r.div<=-6?cssv('--red','#e5676f'):cssv('--blue','#63a9c4');
s+=`<g class="div-dot" data-symbol="${r.sym}" style="cursor:pointer"><circle cx="${X(r.comm)}" cy="${Y(r.basket)}" r="${hot?6:4}" fill="${col}" opacity="${hot?0.95:0.55}"/><text x="${X(r.comm)+8}" y="${Y(r.basket)+3}" fill="${col}" font-size="${hot?10:8.5}" font-weight="${hot?700:400}">${r.sym}</text></g>`}
s+=`<text x="${PL}" y="${H-8}" fill="${gt}" font-size="9">商品 20 日收益 % →</text><text x="${W-PR-4}" y="${PT+8}" fill="${gt}" font-size="9" text-anchor="end">篮子 20 日收益 %</text>`;
return `<svg viewBox="0 0 ${W} ${H}" style="width:100%;height:auto">${s}</svg>`}
function renderDivBoard(){const el=$('divBoard');if(!el)return;const rows=[];
for(const [sym,e] of Object.entries(state.equity||{})){
if(e.div20==null)continue;const p=(state.products||[]).find(x=>x.symbol===sym);if(!p)continue;
rows.push({sym,name:p.name,comm:e.comm_chg20,basket:e.basket_chg20,div:e.div20,corr:e.corr20,signal:e.div_signal||''})}
rows.sort((a,b)=>Math.abs(b.div)-Math.abs(a.div));
const dc=$('divChart');if(dc){dc.innerHTML=divScatterSVG(rows);dc.onclick=e=>{const g=e.target.closest('[data-symbol]');if(g)openDetail(g.dataset.symbol)}}
const ds=$('divSummary');if(ds)ds.textContent=`${rows.length} 品种 · 背离>|6%| 的 ${rows.filter(r=>Math.abs(r.div)>=6).length} 个`;
el.innerHTML=rows.slice(0,12).map(r=>`<div class="div-row" data-symbol="${r.sym}"><b>${r.name}</b><span>${r.comm>=0?'+':''}${r.comm}%</span><span>${r.basket>=0?'+':''}${r.basket}%</span><b class="${r.div>=6?'tone-up':r.div<=-6?'tone-down':'tone-neutral'}">${r.div>=0?'+':''}${r.div}%</b><small>${r.signal}</small></div>`).join('');
const bd=$('divBoard');bd.onclick=e=>{const it=e.target.closest('[data-symbol]');if(it)openDetail(it.dataset.symbol)};}
function renderFocusPool(){const el=$('focusPool');if(!el||!state.products.length)return;
const heat={};state.newsItems.forEach(x=>{(x.tag||'').split('/').forEach(s=>{if(s)heat[s]=(heat[s]||0)+1})});
const scored=state.products.filter(p=>p.last!=null&&p.score!=null).map(p=>{
const tech=Math.abs(p.score);
const r=(p.resistance||[])[0],s=(p.support||[])[0];let edge=null;
if(r&&r>p.last&&(r-p.last)/p.last<0.015)edge='贴近压力 '+fmt(r);
if(s&&s<p.last&&(p.last-s)/p.last<0.015&&(!edge||(p.last-s)/p.last<(r-p.last)/p.last))edge='贴近支撑 '+fmt(s);
const vol=p.vol_regime||'';
const buy=vol.includes('买波'),sell=vol.includes('卖波'),trend=vol.includes('顺势');
const news=heat[p.symbol]||0;
const total=tech+(edge?2:0)+(buy?1.5:0)+(trend?1:0)+news*2.5;
const reasons=[];
if(tech>=5)reasons.push(`共振 ${signed(p.score)} ${p.score>0?'多头':'空头'}结构`);
else if(tech>=3)reasons.push(`共振 ${signed(p.score)}`);
if(edge)reasons.push(edge);
if(buy)reasons.push('低波收敛·买波候选');else if(sell)reasons.push('高波收缩·卖波候选');else if(trend)reasons.push('高波扩张·顺势');
if(news)reasons.push(`小作文×${news}`);
return{p,total,reasons}}).filter(x=>x.total>=4.5||x.reasons.length>=2).sort((a,b)=>b.total-a.total).slice(0,6);
el.innerHTML=scored.map(x=>{const p=x.p,tone=p.score>0.5?'up':p.score<-0.5?'down':'neutral';
return`<article class="focus-card ${tone}" data-symbol="${p.symbol}"><header><b>${p.name} ${p.symbol}</b><span class="${cls(tone)}">${signed(p.score)}</span></header>
<div class="focus-price">${fmt(p.last)}<small class="${(p.change_pct||0)>0?'tone-up':(p.change_pct||0)<0?'tone-down':'tone-neutral'}">${signed(p.change_pct||0)}%</small></div>
<div class="focus-tags">${x.reasons.slice(0,3).map(r=>`<i>${r}</i>`).join('')}</div></article>`}).join('');
const ft=$('focusTime');if(ft)ft.textContent=`${scored.length} 个品种入池`;}
function renderDailyPicks(){const el=$('dailyPicks');if(!el||!state.products.length)return;const ps=state.products.filter(p=>p.last!=null&&p.score!=null);
const strong=[...ps].sort((a,b)=>b.score-a.score).slice(0,3),weak=[...ps].sort((a,b)=>a.score-b.score).slice(0,3);
const near=ps.map(p=>{const r=(p.resistance||[])[0],s=(p.support||[])[0];let best=null;
if(r&&r>p.last)best={d:(r-p.last)/p.last,side:'压力',price:r};
if(s&&s<p.last){const ds=(p.last-s)/p.last;if(!best||ds<best.d)best={d:ds,side:'支撑',price:s}}
return{p,best}}).filter(x=>x.best&&Math.abs(x.p.score)<3.5).sort((a,b)=>a.best.d-b.best.d).slice(0,3);
const item=(p,note)=>{const tone=p.score>0?'tone-up':p.score<0?'tone-down':'tone-neutral';return`<div class="pick-item" data-symbol="${p.symbol}"><b>${p.name} ${p.symbol}</b><span class="pick-score ${tone}">${signed(p.score)}</span><small>${note}</small></div>`};
el.innerHTML='<div class="picks-col"><header><span>共振最强</span><b>STRONG</b></header>'+strong.map(p=>item(p,`${p.ari.split('·')[0].trim()} · ${p.change_pct!=null?signed(p.change_pct)+'%':''}`)).join('')+'</div>'
+'<div class="picks-col"><header><span>共振最弱</span><b>WEAK</b></header>'+weak.map(p=>item(p,`${p.ari.split('·')[0].trim()} · ${p.change_pct!=null?signed(p.change_pct)+'%':''}`)).join('')+'</div>'
+'<div class="picks-col"><header><span>待突破 · 区间边界</span><b>BREAKOUT</b></header>'+near.map(x=>item(x.p,`贴近${x.best.side} ${fmt(x.best.price)} · 距离 ${(x.best.d*100).toFixed(2)}%`)).join('')+'</div>'}
function rankClick(e){const item=e.target.closest('[data-symbol]');if(item)openDetail(item.dataset.symbol)}
function renderMeta(){const m=state.market,age=Math.max(0,Date.now()-new Date(m.updated_at).getTime()),mins=Math.floor(age/60000),delay=mins<=3?'实时':mins<=20?`延迟 ${mins} 分钟`:`数据滞后 ${mins} 分钟`;if($('coverCount'))$('coverCount').textContent=m.total_published;if($('coverFresh'))$('coverFresh').textContent=`${m.fresh} FRESH / ${m.stale} STALE`;if($('coverStatus'))$('coverStatus').textContent=`DATA LINK · ${m.total_published}/${m.total_supported}`;$('headerUpdated').textContent=delay;$('headerUpdated').classList.toggle('quality-warning',mins>20);$('footerUpdated').textContent=`SNAPSHOT ${m.updated_at.slice(0,16).replace('T',' ')}`;$('buildState').innerHTML=`${delay}<br>FRESH ${m.fresh} / STALE ${m.stale}`;}
function renderFilters(){$('sectorFilters').innerHTML=sectors.map(s=>`<button data-sector="${s}" class="${s===state.sector?'active':''}">${s}</button>`).join('')}
function renderRadar(){const sorted=[...state.products].sort((a,b)=>b.score-a.score);renderRank('bullRank',sorted.slice(0,5));renderRank('bearRank',sorted.slice(-5).reverse());const avg=state.products.reduce((s,p)=>s+(+p.score||0),0)/Math.max(1,state.products.length);$('marketBalance').textContent=signed(avg,2);$('marketBalance').className=cls(avg>.4?'up':avg<-.4?'down':'neutral');$('marketBalanceText').textContent=avg>.4?'多头结构占优':avg<-.4?'空头结构占优':'多空结构均衡';const counts={};state.products.forEach(p=>counts[p.sector]=(counts[p.sector]||0)+1);const positions=[[19,25],[72,18],[80,62],[30,75],[55,82],[12,58],[58,12]];$('sectorDots').innerHTML=Object.entries(counts).map(([s,n],i)=>`<i class="sector-dot" style="left:${positions[i%positions.length][0]}%;top:${positions[i%positions.length][1]}%"><span>${s} ${n}</span></i>`).join('')}
function renderRank(id,items){$(id).innerHTML=items.map((p,i)=>`<div class="rank-item" data-symbol="${p.symbol}"><i>0${i+1}</i><div><b>${p.name} ${p.symbol}</b><small>${p.ari} · ${p.macd}</small></div><span class="${cls(p.tone)}">${signed(p.score)}</span></div>`).join('')}
function applyFilters(){const q=$('searchInput')?.value.trim().toLowerCase()||'';let items=state.products.filter(p=>(state.sector==='全部'||p.sector===state.sector)&&(!q||`${p.name} ${p.symbol} ${p.sector} ${p.exchange}`.toLowerCase().includes(q)));const sort=$('sortSelect')?.value||'score-desc';items.sort((a,b)=>sort==='score-desc'?b.score-a.score:sort==='score-asc'?a.score-b.score:sort==='change-desc'?(b.change_pct||0)-(a.change_pct||0):sort==='change-asc'?(a.change_pct||0)-(b.change_pct||0):a.symbol.localeCompare(b.symbol));state.filtered=items;$('resultCount').textContent=`显示 ${items.length} / ${state.products.length} 个航行目标`;renderProducts()}
function renderProducts(){const cards=state.filtered.map(p=>`<article class="product-card ${p.tone}" data-symbol="${p.symbol}"><header><b>${p.symbol}</b><span>${p.exchange}</span></header><h3>${p.name}</h3><div class="price"><b>${fmt(p.last)}</b><span class="${p.change_pct>0?'tone-up':p.change_pct<0?'tone-down':'tone-neutral'}">${signed(p.change_pct||0,2)}%</span></div><div class="data-badge ${p.data_mode==='完整多周期'?'official':'proxy'}">${p.data_mode||'数据状态未知'}</div><footer><span>${p.ari.split('·')[0].trim()} · ${p.sector}${p.stale?' · STALE':''}${p.vol_regime?` · σ${Math.round(p.vol20)}% ${p.vol_regime}`:''}</span><b class="${cls(p.tone)}">${signed(p.score)}</b></footer></article>`).join('');$('productGrid').innerHTML=cards;$('productGrid').classList.toggle('hidden',state.view!=='cards');const rows=state.filtered.map(p=>`<div class="table-row" data-symbol="${p.symbol}"><b>${p.symbol}</b><span>${p.name}</span><span>${p.sector}</span><span>${fmt(p.last)}</span><span class="${p.change_pct>0?'tone-up':'tone-down'}">${signed(p.change_pct||0,2)}%</span><span>${p.ari}</span><b class="${cls(p.tone)}">${signed(p.score)}</b></div>`).join('');$('productTable').innerHTML=`<div class="table-row table-head"><b>代码</b><span>品种</span><span>板块</span><span>现价</span><span>涨跌</span><span>Ari环境</span><b>共振</b></div>${rows}`;$('productTable').classList.toggle('hidden',state.view!=='table')}
async function openDetail(symbol,scroll=true){$('detailEmpty').classList.remove('hidden');$('detailEmpty').innerHTML=`<span>DESCENDING TO ${symbol}</span><h2>读取深层结构档案</h2><p>正在建立四框架数据链路……</p>`;if(scroll)$('detail').scrollIntoView({behavior:'smooth'});try{const d=await fetchJSON(`data/symbols/${symbol}.json?t=${Date.now()}`);state.detail=d;state.frame='D';state.strategyFrame='D';document.querySelectorAll('#chartTabs button').forEach(b=>b.classList.toggle('active',b.dataset.frame==='D'));document.querySelectorAll('#strategyTabs button').forEach(b=>b.classList.toggle('active',b.dataset.frame==='D'));renderDetail(d);$('detailEmpty').classList.add('hidden');$('detailShell').classList.remove('hidden');history.replaceState(null,'',`#detail?symbol=${symbol}`)}catch(e){$('detailEmpty').innerHTML=`<span>DATA LINK INTERRUPTED</span><h2>${symbol} 档案读取失败</h2><p>${e.message}</p>`}}
function renderDetail(d){const p=d.product,q=d.quote,f=d.frameworks,dec=d.decision,m=d.market,analysisAt=d.analysis_updated_at?new Date(d.analysis_updated_at).toLocaleString('zh-CN',{hour12:false}):'未知';$('detailSector').textContent=`${p.sector} / ${p.exch_cn}`;$('detailContract').textContent=String(q.symbol).toUpperCase();$('detailName').textContent=`${p.name} ${p.product}`;$('detailSource').textContent=`报价 ${q.time||'—'} · 策略计算 ${analysisAt} · ${d.snapshot_status==='stale'?'沿用最近成功快照':'数据链路正常'}`;$('detailPrice').textContent=fmt(q.last);$('detailChange').textContent=`${signed(q.change_pct,2)}%`;$('detailChange').className=q.change_pct>0?'tone-up':q.change_pct<0?'tone-down':'tone-neutral';$('detailScore').textContent=signed(dec.score);$('detailScore').className=cls(dec.tone);$('detailBias').textContent=dec.bias;$('detailBias').className=cls(dec.tone);renderFrameworks(f);renderStrategy();renderFundamental(p.product);renderSeats(p.product,d.volatility);renderEquityFold(p.product);renderSurveyFold(p.product);renderChart()}
function seasonalSVG(series,unit){if(!series||series.length<20)return '';
const byYear={};series.forEach(([d,v])=>{const y=d.slice(0,4);(byYear[y]=byYear[y]||[]).push([d,v])});
const years=Object.keys(byYear).sort();let lo=Infinity,hi=-Infinity;series.forEach(([,v])=>{if(v<lo)lo=v;if(v>hi)hi=v});const pad=(hi-lo)*0.08||1;lo-=pad;hi+=pad;
const W=520,H=230,PL=8,PR=44,PT=10,PB=20,x=(mm,dd)=>PL+((mm*30.4+dd)/366)*(W-PL-PR),y=v=>PT+(hi-v)/(hi-lo)*(H-PT-PB);
const cols=['#c9c2a6','#a8b389','#7a9b3d'];let s='';
years.forEach((yr,i)=>{const cur=i===years.length-1;const col=cur?cssv('--green','#57d6a5'):cols[i%cols.length];
const path=byYear[yr].map(([d,v],j)=>`${j?'L':'M'}${x(+d.slice(5,7),+d.slice(8,10)).toFixed(1)},${y(v).toFixed(1)}`).join('');
s+=`<path d="${path}" fill="none" stroke="${col}" stroke-width="${cur?2.2:1.1}" opacity="${cur?1:0.75}"/>`;
if(cur){const ld=byYear[yr][byYear[yr].length-1];s+=`<circle cx="${x(+ld[0].slice(5,7),+ld[0].slice(8,10))}" cy="${y(ld[1])}" r="3" fill="${col}"/><text x="${W-PR+6}" y="${y(ld[1])+3}" fill="${col}" font-size="10">${fmt(ld[1])}</text>`}});
let axis='';['1月','4月','7月','10月'].forEach((lab,i)=>{const xx=x(i*3+1,1);axis+=`<text x="${xx}" y="${H-5}" fill="${cssv('--chart-text','#789198')}" font-size="9">${lab}</text>`});
return `<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${axis}${s}</svg><div class="fund-legend">${years.map((yr,i)=>`<span style="color:${i===years.length-1?cssv('--green','#57d6a5'):cols[i%cols.length]}">— ${yr}</span>`).join('')}<em>${unit||''}</em></div>`}
function renderFundamental(symbol){const card=$('fundamentalCard'),f=state.fundamentals[String(symbol).toUpperCase()];if(!f?.covered){card.classList.add('hidden');return}card.classList.remove('hidden');const link=$('fundamentalLink');
$('fundamentalTitle').textContent='供需主要矛盾';$('fundamentalThesis').innerHTML=(f.contradiction||f.summary||'')+(f.marginal_focus?'<div class=mf>短线边际：'+f.marginal_focus+'</div>':'');
let rows='',series=null,unit='';
if(f.kind==='market_snapshot'){const inv=f.inventory||{},sp=f.spread||{};
const move=inv.latest==null?'未匹配到可靠库存口径':inv.stale?'库存数据滞后':`${inv.comparison} ${inv.change_pct>0?'↑':inv.change_pct<0?'↓':'→'}${fmt(Math.abs(inv.change_pct),1)}%`;
rows=`<div class="fundamental-metric"><div><b>${inv.name||'库存'}</b><small>${inv.source||'知几·料'} · ${inv.end||'—'}</small></div><span>${inv.latest==null?'—':`${fmt(inv.latest)} ${inv.unit||''}`}<small>${move}</small></span></div>`
+`<div class="fundamental-metric"><div><b>主力－下一活跃</b><small>${sp.near_symbol||'—'} / ${sp.far_symbol||'—'}</small></div><span class="${sp.value>0?'tone-up':sp.value<0?'tone-down':'tone-neutral'}">${sp.value==null?'—':signed(sp.value)}<small>${sp.structure||sp.status||'月差待更新'}</small></span></div>`;
series=inv.series;unit=inv.unit;link.classList.add('hidden')}
else{rows=(f.metrics||[]).slice(0,3).map(m=>{const move=m.change_pct==null?'读取失败':m.stale?'数据滞后':`${m.comparison} ${m.change_pct>0?'↑':m.change_pct<0?'↓':'→'}${fmt(Math.abs(m.change_pct),1)}%`;return`<div class="fundamental-metric"><div><b>${m.name}</b><small>${m.why}</small></div><span>${fmt(m.latest)} ${m.unit}<small>${move} · ${m.end||'—'}</small></span></div>`}).join('');
const ms=(f.metrics||[]).filter(m=>m.series&&m.series.length>=20);const head=ms.find(m=>m.id===f.chart_id)||ms[0];series=head?.series;unit=head?.unit;link.href=f.library_url;link.classList.remove('hidden')}
$('fundamentalMetrics').innerHTML=rows;
$('fundChart').innerHTML=seasonalSVG(series,unit)||'<div class="fund-nochart">该品种暂无足够历史序列出图</div>';
const es=(state.essays[String(symbol).toUpperCase()]||[]).slice(0,2);const fold=$('essayFold');
if(fold){if(!es.length){fold.classList.add('hidden')}else{fold.classList.remove('hidden');$('essaySummary').textContent=`近半月 ${es.length} 条`;$('essayBody').innerHTML=es.map(x=>{const s=(x.summary||'').trim();const short=s.length>40?s.slice(0,40)+'…':s;return `<div class="essay-item"><small>${x.date} · ${x.source||'知识星球'}</small><b>${x.title}</b><p>${short}${s.length>40?` <a class="essay-more" href="${x.url}" target="_blank" rel="noopener">查看全文 ↗</a>`:''}</p></div>`}).join('')}}
}
function renderEquityFold(symbol){const fold=$('equityFold');if(!fold)return;const e=state.equity[String(symbol).toUpperCase()];
if(!e||!e.stocks?.length){fold.classList.add('hidden');return}fold.classList.remove('hidden');
const b=e.basket||[],lo=b.length?Math.min(...b):0,hi=b.length?Math.max(...b):1,span=hi-lo||1;
const pts=b.map((v,i)=>`${(i*440/Math.max(1,b.length-1)+30).toFixed(0)},${(52-(v-lo)/span*44).toFixed(1)}`).join(' ');
const chg=e.basket_chg60;
$('equitySummary').textContent=chg!=null?`篮子60日 ${chg>=0?'+':''}${chg}%`:'';
const spark=b.length?`<svg viewBox="0 0 500 60" class="equity-spark"><polyline points="${pts}" fill="none" stroke="${chg>=0?'#7a9b3d':'#c9443f'}" stroke-width="1.8"/><line x1="30" y1="${(52-(100-lo)/span*44).toFixed(1)}" x2="470" y2="${(52-(100-lo)/span*44).toFixed(1)}" stroke="#999" stroke-dasharray="4 3" stroke-width="0.8"/></svg>`:'';
const divHtml=e.div20!=null?`<div class="div-meter ${e.div20>=6?'div-hot':e.div20<=-6?'div-cold':''}"><div class="div-line"><span>商品20日</span><b>${e.comm_chg20>=0?'+':''}${e.comm_chg20}%</b><span>篮子20日</span><b>${e.basket_chg20>=0?'+':''}${e.basket_chg20}%</b><span>相关</span><b>${e.corr20??'—'}</b></div><div class="div-signal">${e.div_signal||''}</div></div>`:'';
$('equityBody').innerHTML=divHtml+spark+e.stocks.map(s=>`<div class="equity-row"><div><b>${s.name}</b><small>${s.code}</small></div><span>${s.price??'—'}</span><span class="${(s.chg||0)>0?'tone-up':(s.chg||0)<0?'tone-down':'tone-neutral'}">${s.chg!=null?(s.chg>=0?'+':'')+s.chg+'%':'—'}<small>日</small></span><span class="${(s.chg5||0)>0?'tone-up':(s.chg5||0)<0?'tone-down':'tone-neutral'}">${s.chg5!=null?(s.chg5>=0?'+':'')+s.chg5+'%':'—'}<small>5日</small></span><span class="${(s.chg20||0)>0?'tone-up':(s.chg20||0)<0?'tone-down':'tone-neutral'}">${s.chg20!=null?(s.chg20>=0?'+':'')+s.chg20+'%':'—'}<small>20日</small></span></div>`).join('')}
function renderSurveyFold(symbol){const fold=$('surveyFold');if(!fold)return;const f=state.fundamentals[String(symbol).toUpperCase()],s=f&&f.survey;if(!s){fold.classList.add('hidden');return}fold.classList.remove('hidden');$('surveySummary').textContent='2026-08 调研/小作文';$('surveyBody').innerHTML=`<p class="survey-text">${s}</p>`}
function renderSeats(symbol,vol){const el=$('seatRows');if(!el)return;const s=state.seats[String(symbol).toUpperCase()];
if(!s){el.innerHTML='<div class="seat-empty">该品种暂无席位数据</div>';}
else{el.innerHTML=Object.entries(s.brokers).map(([b,arr])=>{const last=arr[arr.length-1],prev=arr.length>1?arr[arr.length-2]:last,base=arr.length>5?arr[arr.length-6]:arr[0];
const d1=last-prev,d5=last-base,tone=last>0?'tone-up':last<0?'tone-down':'tone-neutral';
const spark=arr.slice(-8);const lo=Math.min(...spark),hi=Math.max(...spark),span=hi-lo||1;
const pts=spark.map((v,i)=>`${(i*10+4)},${(16-(v-lo)/span*14).toFixed(1)}`).join(' ');
return`<div class="seat-row"><div class="seat-top"><b>${b}</b><span class="${tone}">${last>=0?'+':''}${fmt(last,0)}<small>日${d1>=0?'+':''}${fmt(d1,0)} · 5日${d5>=0?'+':''}${fmt(d5,0)}</small></span></div><svg class="seat-spark" viewBox="0 0 84 20"><polyline points="${pts}" fill="none" stroke="${last>=0?'#7a9b3d':'#c9443f'}" stroke-width="1.5"/></svg></div>`}).join('')}
const v=vol||{};$('seatVol').textContent=v.vol20!=null?`今日波动率 σ20 = ${v.vol20}%（一年分位 ${Math.round((v.vol_pct||0)*100)}%）· ${v.regime||''}`:'';
$('truthNote').textContent='国君/永安/东证净持仓（多-空，前20榜合计，未上榜按0）；持仓量/成交见 quote；数据真源：交易所会员持仓排名 via 新浪/交易所官网，每日收盘后更新。'}
function renderFrameworks(f){const _s=(id,v)=>{const e=$(id);if(e)e.textContent=(v>=0?'+':'')+v.toFixed(2)};_s('fwAri',f.ari.score);_s('fwChan',f.chan.score);_s('fwMacd',f.macd.score);_s('fwGann',f.gann.score);$('ariTone').textContent=f.ari.environment;$('ariTone').className=cls(f.ari.tone);$('ariScore').textContent=signed(f.ari.score);$('ariScore').className=cls(f.ari.tone);$('ariDetail').innerHTML=dl([['多空线',`${fmt(f.ari.line)} · ${f.ari.line_relation}`],['动量',f.ari.momentum],['RSI W/D/60/15',`${fmt(f.ari.rsiW,1)} / ${fmt(f.ari.rsiD,1)} / ${fmt(f.ari.rsi60,1)} / ${fmt(f.ari.rsi15,1)}`]]);$('chanTone').textContent=f.chan.signal;$('chanTone').className=cls(f.chan.tone);$('chanScore').textContent=signed(f.chan.score);$('chanScore').className=cls(f.chan.tone);$('chanDetail').innerHTML=dl([['日线末笔',f.chan.last_pen],['结构',f.chan.structure],['中枢',f.chan.zone?`${fmt(f.chan.zone.low)} — ${fmt(f.chan.zone.high)}`:'未形成稳定中枢'],['背驰',f.chan.divergence],['周 / 60 / 15',`${f.chan.frames.W.last_pen} / ${f.chan.frames['60'].last_pen} / ${f.chan.frames['15'].last_pen}`]]);$('macdTone').textContent=f.macd.summary;$('macdTone').className=cls(f.macd.tone);$('macdScore').textContent=signed(f.macd.score);$('macdScore').className=cls(f.macd.tone);$('macdDetail').innerHTML=dl(f.macd.details.map(x=>[x.frame,`${x.state} · 柱${x.direction} (${signed(x.hist,1)})`]));$('gannTone').textContent=f.gann.line_relation;$('gannTone').className=cls(f.gann.tone);$('gannScore').textContent=signed(f.gann.score);$('gannScore').className=cls(f.gann.tone);$('gannDetail').innerHTML=dl([['摆动',`${fmt(f.gann.swing_low)} — ${fmt(f.gann.swing_high)}`],['八分位',`${f.gann.position_eighth}/8`],['支撑 / 阻力',`${fmt(f.gann.support)} / ${fmt(f.gann.resistance)}`],['1×1线',fmt(f.gann.line_1x1)],['时间窗',f.gann.next_time_window||'暂无临近窗口']])}
function renderDecisions(dec){for(const side of ['long','short']){const x=dec[side],pre=side;$(`${pre}Priority`).textContent=x.priority;$(`${pre}Trigger`).textContent=x.trigger_text;$(`${pre}Detail`).innerHTML=dl([[side==='long'?'回踩入场':'反抽入场',range(x.entry)],['目标 T1 / T2',`${fmt(x.targets[0])} / ${fmt(x.targets[1])}`],['止损 / 失效',`${fmt(x.stop)} · ${x.invalid}`],['每手理论风险',`¥${fmt(dec.risk[`${side}_risk_per_lot`],0)}`]]);$(`${pre}Confirm`).textContent=x.confirmation}}
function renderCandidates(dec){for(const [key,pre] of [['left_long','leftLong'],['left_short','leftShort']]){const x=dec[key];if(!x)continue;$(`${pre}Priority`).textContent=`${x.priority} · ${x.status}`;$(`${pre}Zone`).textContent=range(x.zone);$(`${pre}Trigger`).textContent=x.trigger_text;$(`${pre}Detail`).innerHTML=dl([['失效位',fmt(x.stop)],['目标 T1 / T2',`${fmt(x.targets[0])} / ${fmt(x.targets[1])}`],['每手理论风险',`¥${fmt(x.risk_per_lot,0)}`]])}}
function renderStrategy(){const d=state.detail;if(!d)return;const dec=d.strategies?.[state.strategyFrame]||d.decision;$('strategyHorizon').textContent=`${dec.label||'日线'} · ${dec.horizon||dec.bias}`;$('strategyQuality').textContent=`${dec.bias} · ${dec.quality_note||dec.confidence||'—'}`;renderCandidates(dec);renderDecisions(dec);renderLevels(dec,d.quote.last)}
function renderLevels(dec,price){const vals=[...dec.support,price,...dec.resistance].sort((a,b)=>b-a),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;$('levelMap').innerHTML=vals.map(v=>`<div class="level-item"><span>${v===price?'现价':v>price?'阻力':'支撑'}</span><div class="level-track"><i style="width:${20+80*(v-min)/span}%"></i></div><b class="${v===price?'tone-neutral':''}">${fmt(v)}</b></div>`).join('')}
function renderChart(){const d=state.detail;if(!d)return;const payload=d.charts[state.frame],bars=payload?.bars||[];if(!bars.length){$('priceChart').textContent='暂无K线';return}const W=1100,H=420,P={l:55,r:70,t:18,b:32},pw=W-P.l-P.r,ph=H-P.t-P.b,all=[];bars.forEach(b=>all.push(b.low,b.high));['ma5','ma20','ma60'].forEach(k=>(payload[k]||[]).forEach(v=>v!=null&&all.push(v)));let min=Math.min(...all),max=Math.max(...all),m=(max-min)*.06||1;min-=m;max+=m;const x=i=>P.l+(i+.5)*pw/bars.length,y=v=>P.t+(max-v)*ph/(max-min),cw=Math.max(1,Math.min(7,pw/bars.length*.62));let svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">`;for(let i=0;i<6;i++){const yy=P.t+i*ph/5,val=max-i*(max-min)/5;svg+=`<line x1="${P.l}" y1="${yy}" x2="${W-P.r}" y2="${yy}" stroke="${cssv('--chart-grid','#10272e')}"/><text x="${W-P.r+8}" y="${yy+4}" fill="${cssv('--chart-text','#557078')}" font-size="10">${fmt(val)}</text>`}bars.forEach((b,i)=>{const up=b.close>=b.open,c=up?cssv('--green','#57d6a5'):cssv('--red','#e5676f'),xx=x(i);svg+=`<line x1="${xx}" y1="${y(b.high)}" x2="${xx}" y2="${y(b.low)}" stroke="${c}"/><rect x="${xx-cw/2}" y="${Math.min(y(b.open),y(b.close))}" width="${cw}" height="${Math.max(1,Math.abs(y(b.open)-y(b.close)))}" fill="${c}"/>`});const line=(values,color)=>{let path='',on=false;values.forEach((v,i)=>{if(v==null){on=false;return}path+=`${on?'L':'M'}${x(i).toFixed(1)},${y(v).toFixed(1)} `;on=true});return`<path d="${path}" fill="none" stroke="${color}" stroke-width="1.3"/>`};svg+=line(payload.ma5,cssv('--amber','#dbba6b'))+line(payload.ma20,cssv('--blue','#63a9c4'))+line(payload.ma60,cssv('--violet','#9b86bc'));const step=Math.max(1,Math.floor(bars.length/6));for(let i=0;i<bars.length;i+=step)svg+=`<text x="${x(i)}" y="${H-9}" text-anchor="middle" fill="${cssv('--chart-text','#506a70')}" font-size="9">${String(bars[i].time).slice(5,16)}</text>`;$('priceChart').innerHTML=svg+'</svg>'}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}
let installPrompt=null;
function setupPWA(){const install=$('installApp'),standalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true,mobile=window.matchMedia('(max-width: 800px)').matches;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('service worker unavailable',e));if(standalone)document.documentElement.classList.add('standalone');else if(mobile)install.classList.remove('hidden');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;if(!standalone)install.classList.remove('hidden')});install.addEventListener('click',async()=>{if(!installPrompt){toast(/iPhone|iPad|iPod/i.test(navigator.userAgent)?'在 Safari 中点“分享”，再选“添加到主屏幕”':'请用浏览器菜单选择“安装应用”或“添加到主屏幕”');return}installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;install.classList.add('hidden')});window.addEventListener('appinstalled',()=>{installPrompt=null;install.classList.add('hidden');toast('渊行已安装到主屏幕')})}
function renderMacro(e){if(!e)return;$('macroTime').textContent=new Date(e.released_at).toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'});$('macroStance').textContent=e.stance;$('macroTitle').textContent=e.title;$('macroVerify').textContent=e.verification;$('macroConclusion').textContent=e.conclusion;$('macroMetrics').innerHTML=e.metrics.map(x=>`<div><span>${x.name}</span><b>${x.actual}</b><small>预期 ${x.consensus} · 前值 ${x.previous}</small></div>`).join('');$('macroTransmission').innerHTML=e.transmission.map(x=>`<p><b>${x.asset} · ${x.view}</b><span>${x.detail}</span></p>`).join('');$('macroNext').innerHTML=e.next.map(x=>`<p><b>${x.time} · ${x.event}</b><span>${x.watch}</span></p>`).join('');$('macroSources').innerHTML=e.sources.map(x=>`<a href="${x.url}" target="_blank" rel="noopener">${x.name} ↗</a>`).join('')}
async function loadNews(){try{const d=await fetchJSON(`data/news.json?t=${Date.now()}`);state.newsItems=d.items||[];const el=$('newsGrid');if(!el)return;$('newsTime').textContent=`更新 ${String(d.updated_at||'').slice(0,10)}`;el.innerHTML=(d.items||[]).map(x=>`<a class="news-card" href="${x.url}" target="_blank" rel="noopener"><header><span class="news-sector">${x.sector}</span><span class="news-tag">${x.tag||''}</span><small>${x.date}</small></header><h4>${x.title}</h4><p>${x.summary}</p><footer>${x.source} ↗</footer></a>`).join('')}catch(e){console.warn('news unavailable',e)}}
async function loadMacro(){try{renderMacro((await fetchJSON(`data/macro.json?t=${Date.now()}`)).event)}catch(e){console.warn('macro unavailable',e)}}
let booted=false;function boot(){if(booted)return;booted=true;initTheme();if(window.acctInit)acctInit();loadMacro();loadNews();init();window.setInterval(refreshLive,30000)}setupPWA();window.addEventListener('yafco:authorized',boot);if(window.YAFCOAccess?.allowed())boot();
